CREATE TABLE CLIENTES (
    CLIENTE_ID NUMBER PRIMARY KEY,
    NOMBRE VARCHAR2(100),
    APELLIDO VARCHAR2(100),
    EMAIL VARCHAR2(150),
    GENERO VARCHAR2(20),
    FECHA_REGISTRO DATE,
    CIUDAD VARCHAR2(100),
    PAIS VARCHAR2(100)
);

CREATE TABLE CATEGORIAS (
    CATEGORIA_ID NUMBER PRIMARY KEY,
    NOMBRE_CATEGORIA VARCHAR2(100)
);

CREATE TABLE PRODUCTOS (
    PRODUCTO_ID NUMBER PRIMARY KEY,
    NOMBRE_PRODUCTO VARCHAR2(150),
    PRECIO NUMBER(10,2),
    CATEGORIA_ID NUMBER,
    CONSTRAINT FK_PRODUCTO_CATEGORIA
        FOREIGN KEY (CATEGORIA_ID)
        REFERENCES CATEGORIAS(CATEGORIA_ID)
);

CREATE TABLE ORDENES (
    ORDEN_ID NUMBER PRIMARY KEY,
    CLIENTE_ID NUMBER,
    FECHA_ORDEN DATE,
    METODO_PAGO VARCHAR2(50),
    ESTADO VARCHAR2(50),
    TOTAL NUMBER(10,2),
    CONSTRAINT FK_ORDEN_CLIENTE
        FOREIGN KEY (CLIENTE_ID)
        REFERENCES CLIENTES(CLIENTE_ID)
);

CREATE TABLE DETALLE_ORDEN (
    DETALLE_ID NUMBER PRIMARY KEY,
    ORDEN_ID NUMBER,
    PRODUCTO_ID NUMBER,
    CANTIDAD NUMBER,
    PRECIO_UNITARIO NUMBER(10,2),
    SUBTOTAL NUMBER(10,2),
    CONSTRAINT FK_DETALLE_ORDEN
        FOREIGN KEY (ORDEN_ID)
        REFERENCES ORDENES(ORDEN_ID),
    CONSTRAINT FK_DETALLE_PRODUCTO
        FOREIGN KEY (PRODUCTO_ID)
        REFERENCES PRODUCTOS(PRODUCTO_ID)
);


select table_name
from user_tables;